/// Flutter icons Jana
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Jana
///      fonts:
///       - asset: fonts/Jana.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Jana {
  Jana._();

  static const _kFontFam = 'Jana';
  static const _kFontPkg = null;

  static const IconData addfinger = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData fingerprint = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData call_end = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData searrchfinger = IconData(0xe803, fontFamily: _kFontFam);
}
